#!/usr/bin/env python3
"""
生成内置中文字体 C 文件
使用 lv_font_conv 工具从 TTF 字体生成 LVGL 可用的字体
支持生成可直接编译的 C 文件
"""

import os
import sys
import subprocess

# 配置
FONT_NAME = "GenJyuuGothic"
TTF_FILE = "GenJyuuGothic-Monospace-Light-2.ttf"
CHARS_FILE = "common_chinese_chars.txt"
OUTPUT_C_FILE = "builtin_chinese_font.c"
OUTPUT_HEADER_FILE = "builtin_chinese_font.h"
FONT_VAR_NAME = "lv_font_builtin_chinese_16"

# 字体参数
FONT_SIZE = 16  # 字体大小
BPP = 4        # 每像素位数 (4 = 16 级灰度)

def read_chinese_chars(filepath):
    """读取常用汉字列表"""
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()
        # 去除空白字符，只保留汉字
        chars = ''.join(content.split())
        # 去重并排序
        unique_chars = sorted(set(chars))
        return unique_chars

def generate_font_c_file(ttf_path, chars, size, bpp, output_c):
    """使用 lv_font_conv 直接生成 C 文件"""

    # 构建 symbols 参数 - 将所有字符作为符号传入
    symbols_str = ''.join(chars)

    cmd = [
        'lv_font_conv',
        '--size', str(size),
        '--bpp', str(bpp),
        '--font', ttf_path,
        '--symbols', symbols_str,
        '--format', 'lvgl',  # 生成 LVGL C 格式
        '-o', output_c,
        '--force-fast-kern-format'
    ]

    print(f"Running: lv_font_conv --size {size} --bpp {bpp} --font {ttf_path} --symbols <{len(chars)} chars> --format lvgl -o {output_c}")

    try:
        result = subprocess.run(cmd, capture_output=True, text=True, check=True)
        print(result.stdout)
        if result.stderr:
            print("Info:", result.stderr)
        return True
    except subprocess.CalledProcessError as e:
        print(f"Error running lv_font_conv: {e}")
        print(f"stdout: {e.stdout}")
        print(f"stderr: {e.stderr}")
        return False
    except FileNotFoundError:
        print("Error: lv_font_conv not found!")
        print("\nPlease install lv_font_conv:")
        print("  pip install lv_font_conv")
        print("\nOr install the standalone version:")
        print("  Download from: https://github.com/lvgl/lv_font_conv/releases")
        return False

def modify_generated_c_file(input_c, output_c, var_name, font_name):
    """修改生成的 C 文件，添加必要的声明和包装"""

    with open(input_c, 'r', encoding='utf-8') as f:
        content = f.read()

    # 添加头文件和保护
    header = f"""/**
 * @file {os.path.basename(output_c)}
 * @brief Auto-generated built-in Chinese font for LVGL
 *
 * Font: {font_name}
 * Size: {FONT_SIZE}px
 * BPP: {BPP}
 *
 * Generated by generate_builtin_font_v2.py
 */

#include "lvgl.h"

#ifdef __cplusplus
extern "C" {{
#endif

"""

    # 添加外部访问函数声明
    footer = """

#ifdef __cplusplus
}
#endif

"""

    # 在文件开头添加头文件
    content = header + content + footer

    # 写入输出文件
    with open(output_c, 'w', encoding='utf-8') as f:
        f.write(content)

    # 获取文件大小
    file_size = os.path.getsize(output_c)
    print(f"Generated C file: {output_c} ({file_size} bytes, {file_size/1024:.1f} KB)")

    return file_size

def generate_header_file(header_file, font_c_name, font_var_name):
    """生成头文件"""

    h_content = f"""/**
 * @file {os.path.basename(header_file)}
 * @brief Built-in Chinese font declaration
 */

#ifndef BUILTIN_CHINESE_FONT_H
#define BUILTIN_CHINESE_FONT_H

#include "lvgl.h"

#ifdef __cplusplus
extern "C" {{
#endif

/* Built-in Chinese font - {FONT_SIZE}px */
extern const lv_font_t {font_var_name};

/**
 * @brief Get the built-in Chinese font
 * @return Pointer to the built-in LVGL font
 */
static inline const lv_font_t* get_builtin_chinese_font(void)
{{
    return &{font_var_name};
}}

/**
 * @brief Check if built-in Chinese font is available
 * @return Always returns true (font is compiled in)
 */
static inline bool builtin_font_is_available(void)
{{
    return true;
}}

#ifdef __cplusplus
}}
#endif

#endif /* BUILTIN_CHINESE_FONT_H */
"""

    with open(header_file, 'w', encoding='utf-8') as f:
        f.write(h_content)

    print(f"Generated header file: {header_file}")

def main():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    os.chdir(script_dir)

    print("=" * 70)
    print("Built-in Chinese Font Generator for LVGL")
    print("=" * 70)

    # 检查文件是否存在
    if not os.path.exists(TTF_FILE):
        print(f"\nError: TTF file not found: {TTF_FILE}")
        print(f"Current directory: {os.getcwd()}")
        print(f"Please place {TTF_FILE} in the same directory as this script.")
        print("\nYou can download GenJyuuGothic font from:")
        print("  https://github.com/ButTaiwan/genjyuu-font")
        return 1

    if not os.path.exists(CHARS_FILE):
        print(f"\nError: Characters file not found: {CHARS_FILE}")
        print(f"Current directory: {os.getcwd()}")
        return 1

    # 读取字符集
    print(f"\n[1/4] Reading Chinese characters from {CHARS_FILE}...")
    chars = read_chinese_chars(CHARS_FILE)
    print(f"      Found {len(chars)} unique characters")

    if len(chars) == 0:
        print("Error: No characters found in file!")
        return 1

    # 生成 C 文件
    print(f"\n[2/4] Generating font C file with lv_font_conv...")
    print(f"      Font: {TTF_FILE}")
    print(f"      Size: {FONT_SIZE}px, BPP: {BPP}")
    print(f"      Output: {OUTPUT_C_FILE}")

    temp_c_file = "temp_font.c"
    if not generate_font_c_file(TTF_FILE, chars, FONT_SIZE, BPP, temp_c_file):
        print("\nError: Failed to generate font C file")
        print("\nTroubleshooting:")
        print("  1. Make sure lv_font_conv is installed:")
        print("       pip install lv_font_conv")
        print("  2. Check that the TTF file is valid")
        print("  3. Try with fewer characters to reduce memory usage")
        return 1

    # 修改生成的 C 文件
    print(f"\n[3/4] Processing generated C file...")
    file_size = modify_generated_c_file(temp_c_file, OUTPUT_C_FILE, FONT_VAR_NAME, FONT_NAME)

    # 生成头文件
    print(f"\n[4/4] Generating header file...")
    generate_header_file(OUTPUT_HEADER_FILE, OUTPUT_C_FILE, FONT_VAR_NAME)

    # 清理临时文件
    if os.path.exists(temp_c_file):
        os.remove(temp_c_file)
        print(f"\n[Cleanup] Removed temporary file: {temp_c_file}")

    print("\n" + "=" * 70)
    print("Generation complete!")
    print("=" * 70)
    print(f"\nGenerated files:")
    print(f"  - {OUTPUT_C_FILE} ({file_size/1024:.1f} KB)")
    print(f"  - {OUTPUT_HEADER_FILE}")
    print(f"\nCharacter set: {len(chars)} common Chinese characters")
    print(f"Font: {FONT_NAME}, {FONT_SIZE}px, {BPP} bpp")
    print("\nNext steps:")
    print(f"  1. These files are already in the correct directory:")
    print(f"     {os.path.abspath(OUTPUT_C_FILE)}")
    print(f"     {os.path.abspath(OUTPUT_HEADER_FILE)}")
    print(f"  2. Update CMakeLists.txt to include builtin_chinese_font.c")
    print(f"  3. In your code, use: #include \"builtin_chinese_font.h\"")
    print(f"     Then call: get_builtin_chinese_font()")
    print("=" * 70)

    return 0

if __name__ == "__main__":
    sys.exit(main())
