/**
 * @file embedded_menu_default_font.h
 * @brief Embedded menu_default_font font - minimal version for menu
 * 
 * Auto-generated by embed_font.py
 * Original font: 0x0 pixels
 * Embedded characters: 0 (essential menu chars + 3595 CJK chars)
 */

#ifndef __EMBEDDED_MENU_DEFAULT_FONT_H__
#define __EMBEDDED_MENU_DEFAULT_FONT_H__

#include <stdint.h>

// Font header information
#define EMBEDDED_FONT_WIDTH 0
#define EMBEDDED_FONT_HEIGHT 0
#define EMBEDDED_FONT_GLYPH_SIZE 0
#define EMBEDDED_FONT_CHAR_COUNT 0

// Font character data (organized by Unicode codepoint)
extern const uint8_t g_menu_default_font_data[];
extern const uint32_t g_menu_default_font_data_size;

// Character index map for quick lookup
// Maps Unicode -> offset in data array
extern const uint16_t g_menu_default_font_index[];
extern const uint16_t g_menu_default_font_index_count;

#endif // __EMBEDDED_MENU_DEFAULT_FONT_H__
