/**
 * @file embedded_menu_default_font.c
 * @brief Embedded menu_default_font font data
 * 
 * Auto-generated by embed_font.py
 * Font size: 0x0 pixels
 * Glyph size: 0 bytes
 * Total characters: 0
 */

#include "embedded_menu_default_font.h"

// Embedded font glyph data
// Each character is stored as 0-byte bitmap
const uint8_t g_menu_default_font_data[] = {

};

const uint32_t g_menu_default_font_data_size = sizeof(g_menu_default_font_data);

// Character index (Unicode codepoint -> offset in data)
// Format: [codepoint_low, codepoint_high, offset_low, offset_high]
const uint16_t g_menu_default_font_index[] = {

};

const uint16_t g_menu_default_font_index_count = 0;
